--Author: Group 2
-- This script was authored by Group 2 for database operations.
-- It includes procedures for map retrieval and table creation.
-- The 'maps' table stores specific map data used in the application.
-- Procedures 'MapsById' and 'MapsBynom' enable data retrieval based on ID or name.
-- Data inserted into the 'maps' table represents sample map information.

CREATE DATABASE IF NOT EXISTS jpublankproject;
USE jpublankproject;

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";




--
-- DataBase :  `boulderdash`
--

DELIMITER $$
--
-- Procedures
--
DROP PROCEDURE IF EXISTS `MapsById`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `MapsById` (IN `p_id` INT)  NO SQL
SELECT * FROM maps WHERE id = p_id$$

DROP PROCEDURE IF EXISTS `MapsBynom`$$
CREATE DEFINER=`root`@`localhost` PROCEDURE `MapsBynom` (IN `d_nom` CHAR(10))  NO SQL
SELECT * FROM maps WHERE nom=d_nom$$

DELIMITER ;

-- --------------------------------------------------------

--
-- Table Structure: `maps`
--

DROP TABLE IF EXISTS `maps`;
CREATE TABLE IF NOT EXISTS `maps` (
                                      `id` int(11) NOT NULL AUTO_INCREMENT,
                                      `nom` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
                                      `diamond` int(11) NOT NULL DEFAULT '0',
                                      `map` text CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
                                      PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=latin1;

--
-- Data Loading for table `maps`
--

INSERT INTO `maps` (`id`, `nom`, `diamond`, `map`) VALUES
(1, 'map1', 200, 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMTPTTPTTMTPTTTDTMTTT TPTM TMTTTTMTTPPTTMMTTTTTTTMTTTTTT M  P TTTM TT TTTMTTTT TMM              P PP      P  D        P MMDTTTTTTMTPTTTTPMTPT TT MTTPTTDTMTTPTPTMMTTTTTTTMTPTTTTPMTPT  TTMTTTTTPTMTTT TTMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMMMTTTTPPTMTT TTTTMTTT TTPMTTTT TTMTTTTT MMTTTTTTTMTT TTTTMTTT TTTMTTTTPT MTTTTTPMM          P                 P        PMMPTTPTTTMTTTTPTTMTTPPTTTMTTTTTTDM TTTTTMMPTTTTPTMTTPTTPTMTTTPTPPMTTTTTTTMPTTTPTMMTPTTTTTMTTTPTTTMTTT T  MTTTTTTTMPPTTPTMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMMMPT S TTMTTTTPTPMTTT TTTMTPDTT TMTTTTTTMMTTTTT TM TTTTTTMTTD TTTM TT TPTMT T  TMM        P                  P P   P PP MMDTT TPTMPTTTTPTMTPT TTPMTPTPTTTMTTTTTTMMTTTTTPTMPTTDTTTMTTT  TTMTTPTTTTMTTT   MMTDTTTP MTT TTTTMTJD PTTMT TTTTTMTTTPPPMMTPTTTTPMTTPTTPTMTBT TTTMTTTTPTPMTTTTPTMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'),
(2, 'map2', 200, 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMJTTTTTPTTTTTTTTTTTTTTTTTTTTPTTTTTTTTPTMMTTTTTPTTTTTTTTTTTDTTTTTTTTTTTTPTTTTTTTMMTTTTTTTTPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTMMPTTTTTTTTTTTPPTTTTTTTTTTTTTTTTDTTTTTTTMMTTTTTTTTTTTTTTTTTTTPTTTTTTTTTTTTTTTTTTMMTPTTTTTTTTTTTTTTTTTTTTTPTTTTTTTTTPTTTTMMTTPTTTTTPTTTTTTTTTTTPTTPTTPTTTTTTTTTTPMMTTTTTTPTTTTTTPTTTTTDTTTTTTPTTTTTTTTPTTMMTTTTTTTTS TTTPTTS TTTTTTS TTTTTTS TTTTMMTTTTTTTT STTTPTT STTTTTT STTTTTT STPTTMMTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTMMTTTPTTTTTTTTTTTTTTTTTTTTPTTTTTTDTTTTTTMMTTTPTTTTTPTTTTTTTTTTTTSTTTTTTTTTTTTTTTMMTTTTTTPTTTTTTTTTTTTPTTTTTTTTTDTTTTTTTPMMTTTTTTTTTTTTPTTTTTTTPTTTTSTTTTTTTTTTTTMMTTPTTTTTTTTTTTTTTTPTTTTTTTTTTTTTTTTTTTMMTTTTTTTDTTTTTTTTTTTTTTPTTTTTTTTPTTTTTTMMTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPTTPTTMMTTTPTTTTTPTPPTTTTTTDTTTTTTTTTTTTTPTTTTMMTTTTTTTTTPTPPTTTTTTTTTPTTPTPTTTTTTTTTBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'),
(3, 'map3', 200, 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMPTMMTMPPTMTTTPMPTTPTTTTMTTTPTTTTTPMTDTMMTTJMTDTPTMTTTMMMTTMTPTTTTPTTPTPTTTMTMPMMTSTTMTTPDTTPTTTTMTTTTTPTMMPTTTTTTTMTMMMMDTMTTMPMPTTPTTTTMTTTPTTTTTTPTPPTTSSTTPMMPTMTTTMTTPTMMTTPTMMDTTTSTTTPTPPTTTTTTMMMPPTTPTTTTMTTTPTTSTTTPTPPTTTTTTPTTDMMTTMMTTPTMMTTPTPPTTTMTTTTPTPPTTTTTTMTTPTMTPMMTTMTTTDTTTTTTDTPTTMMPTTPTMTMPTTMPTTDTPMMPTPTTTTMTMMTPDTPTTMMPTTPTTDTMTTTMTTPTMMMTPTMMTTTTTPPMPTTDTMTMPTTMPTTTMPTTDTPTMMMMTMMTTSTTTPPMPTTPTMTMPTTMPTTTTMMTTPTMMMMTMTPTPTMTTTMMPTTPTTTTMTTTPTTTTTMMTPTMMMMTMTPTPTMTDTMTMPTTMPTTTTPTTPTPPTTTTMTTTMMMTTMPMPTTPTTTTMTTTDTTTMTPMTTTTTTMTMMTDMMMTTTMMPTTMTDTTTMPTTPTPTTTPTMPTTSTTTMTTMMMTDTTTTPTMMTTPTMMPTTTTTTTPTMPTTTTTTMTTMMTTPTTTTMTTTPTTTTTTPTPPTTTTTTMSTPTMTTTMMMPTMMTTPTMMTTTMTTTTPTPPTTTTTTMTTPDTTPTTBMMTTTPTTTTTTPTPDTTTTTTPTTTMMTTMPTTDTMTTMMPPTTTMTTTTTPTPDTTTTTTMTTPTMDTDTPMTPTTTMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'),
(4, 'map4', 200, 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMJTTTTTPTTTTTTTTTTTTTTTTTTTTPTTTTTTTTPTMMTTTTTPTTTTTTTTTTTDTTTTTTTTTTTTPTTTTTTTMMTTTTTTTTPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTMMPTTTTTTTTTTTTTTTTTTTTTTTTTTTTTDTTTTTTTMMTTTTTTTTTTTTTTTTTTTPTTTTTTTTTTTTTTTTTTMMTPTTTTTTTTTTTTTTTTTTTTTPTTTTTTTTTPTTTTMMTTPTTTTTPTTTTTTTTTTTPTTPTTTTTTTTTTTTTPMMTTTTTTPTTTTTTPTTTTTDTTTTTTTTTTTTTTTPTTMMTTTTTTTT  TTTPTT  TTTTTT  TTTTTT  TTTTMMTTTTTTTT STTTPTT STTTTTT STTTTTT STPTTMMTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTMMTTTPTTTTTTTTTTTTTTTTTTTTPTTTTTTDTTTTTTMMTTTPTTTTTPTTTTTTTTTTTTTTTTTTTTTTTTTTTTMMTTTTTTPTTTTTTTTTTTTPTTTTTTTTTDTTTTTTTPMMTTTTTTTTTTTTPTTTTTTTPTTTTTTTTTTTTTTTTTMMTTPTTTTTTTTTTTTTTTPTTTTTTTTTTTTTTTTTTTMMTTTTTTTDTTTTTTTTTTTTTTPTTTTTTTTPTTTTTTMMTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTPTTPTTMMTTTPTTTTTPTPPTTTTTTDTTTTTTTTTTTTTPTTTTMMTTTTTTTTTPTPPTTTTTTTTTPTTPTPTTTTTTTTTBMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM'),
(5, 'map5', 200, 'MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMTPTTPTTMTPTTTDTMTTT TPTM TMTTTTMTTPPTTMMTTTTTTTMTTTSTT M  P TTTM TT TTTMTTTT TMM              P PP      P  D        P MMDTTTTTTMTPTTTTPMTPT TT MTTPTTDTMTTPTPTMMTTTTTTTMTPTTTTPMTPT  TTMTTTTTPTMTTT TTMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMMMTTTTPPTMTT TTTTMTTT TTPMTTTT TTMTTSST MMTTTTTTTMTT TTTTMTTT TTTMTTTTPT MTTTTTPMM          P                 P        PMMPTTPTTTMTTTTPTTMTTPPTTTMTTTTTTDM TTTTTMMPTTTTPTMTTPTTPTMTTTPTPPMTTTTTTTMPTSTPTMMTPTTTTTMTTTPTTTMTTT T  MTTTMTTTMPPTTPTMMMMMMMMMMMMMMMMMMMMM MMMMMMMMMMMMMMMMMMMMPT S TTMTTTTPTPMTTT TTTMTPDTT TMTTTTTTMMTTTTT TM TTTTTTMTTD TTTM TT TPTMT T  TMM        P                  P P   P PP MMDTT TPTMPTTTTPTMTPT TTPMTPTPTTTMTTTTTTMMTTTSTPTMPTTDTTTMTTT  TTMTTPTTTTMTTT   MMTDTSTP MTT TTTTMTJD PTTMT TTSTTMTTTPPPMMTPTTTTPMTTPTTPTMTBT TTTMTTTTPTPMTTTTPTMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM');
COMMIT;

